// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_COLLEGE_TRENDS_REQUEST = 'GET_COLLEGE_TRENDS_REQUEST';
export const GET_COLLEGE_TRENDS_SUCCESS = 'GET_COLLEGE_TRENDS_SUCCESS';
export const GET_COLLEGE_TRENDS_FAILURE = 'GET_COLLEGE_TRENDS_FAILURE';


export const TOGGLE_SIGNUP_MODAL = 'TOGGLE_SIGNUP_MODAL';
export const TOGGLE_SIGNIN_MODAL = 'TOGGLE_SIGNIN_MODAL';

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const LOGOUT = "LOGOUT";

export const GET_INSTITUTES_REQUEST = 'GET_INSTITUTES_REQUEST';
export const GET_INSTITUTES_SUCCESS = 'GET_INSTITUTES_SUCCESS';
export const GET_INSTITUTES_FAILURE = 'GET_INSTITUTES_FAILURE';

export const GET_BLOG_REQUEST = 'GET_BLOG_REQUEST';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAILURE = 'GET_BLOG_FAILURE';

export const GET_INSTITUTE_REQUEST = "GET_INSTITUTE_REQUEST";
export const GET_INSTITUTE_SUCCESS = "GET_INSTITUTE_SUCCESS";
export const GET_INSTITUTE_FAILURE = "GET_INSTITUTE_FAILURE";

export const GET_EXAMS_REQUEST = 'GET_EXAMS_REQUEST';
export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS';
export const GET_EXAMS_FAILURE = 'GET_EXAMS_FAILURE';